name: Terraform Pipeline

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply Terraform plan?"
        required: false
        default: "no"
      destroy:
        description: "Destroy infrastructure?"
        required: false
        default: "no"

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_LOG: INFO
      TF_WORKSPACE: default
      AWS_REGION: us-east-1

    steps:

      - name: ğŸ”¹ Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: ğŸ—‘ Clean Terraform cache
        run: |
          rm -rf .terraform
          rm -f tfplan tf_apply.log tf_plan.log tf_init.log

      - name: ğŸ”§ Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.6"

      - name: ğŸš€ Terraform Init
        run: terraform init -input=false -reconfigure | tee tf_init.log

      - name: ğŸ” Terraform Validate
        run: terraform validate | tee tf_validate.log

      - name: ğŸ“„ Terraform Plan
        run: terraform plan -out=tfplan | tee tf_plan.log

      - name: ğŸ“¤ Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-logs
          path: |
            tf_init.log
            tf_validate.log
            tf_plan.log

      - name: ğŸš€ Optional Terraform Apply
        if: ${{ github.event.inputs.apply == 'yes' }}
        run: terraform apply -auto-approve tfplan | tee tf_apply.log

      - name: ğŸ“¤ Upload Apply Log
        if: ${{ github.event.inputs.apply == 'yes' }}
        uses: actions/upload-artifact@v4
        with:
          name: terraform-apply-log
          path: tf_apply.log

      - name: ğŸ—‘ Optional Terraform Destroy
        if: ${{ github.event.inputs.destroy == 'yes' }}
        run: terraform destroy -auto-approve | tee tf_destroy.log

      - name: ğŸ“¤ Upload Destroy Log
        if: ${{ github.event.inputs.destroy == 'yes' }}
        uses: actions/upload-artifact@v4
        with:
          name: terraform-destroy-log
          path: tf_destroy.log
